title = "Eric Rochester"
# The URL the site will be built for
base_url = "https://www.ericrochester.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "hermit_zola"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
home_subtitle = "Writer and Software Developer"

footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

hermit_menu = [
  { link = "/posts", name = "Posts" },
  { link = "/about", name = "About" },
]

hermit_social = [
  { name = "github", link = "https://github.com/erochest" },
  { name = "email", link = "mailto:author@domain.com" },
  { name = "linkedin", link = "https://www.linkedin.com/in/erochester/" },
]


[extra.highlightjs]
enable = true
clipboard = true
theme = "vs2015"

# [extra.disqus]
# enable = false
# Take this from your Disqus account
# shortname = "my-supa-dupa-blog"

[extra.author]
name = "Eric Rochester"
email = "erochest@gmail.com"

# [extra.google_analytics]
# enable = false
# id = "UA-4XXXXXXX-X"
